SUBROUTINE FBULGE(X,Y,Z,AX,AY,AZ,G,MBULGE,BB)
!
!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
!
! Compute the acceleration of a particle moving within the gravitational potential 
! generated by a Plummer-shere bulge. 
!
! Coded by L. J. Rossi (Melbourne, 2014)
!
!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
!
  IMPLICIT NONE
!
  REAL (8) X,Y,Z,AX,AY,AZ,G,MBULGE,BB,R,CMB
!
  R = SQRT(X**2.0 + Y**2.0 + Z**2.0)
  CMB = -G*MBULGE/(R**2.0 + BB**2.0)**(1.5)
!
! Compute the accelerations
  AX = CMB*X
  AY = CMB*Y
  AZ = CMB*Z
!
END SUBROUTINE FBULGE
