SUBROUTINE FDISC(X,Y,Z,AX,AY,AZ,G,MDISC,AD,BD)
!
!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
!
! Compute the acceleration of a particle moving within the gravitational potential 
! generated by a Miyamoto-Nagai disc. 
!
! Coded by L. J. Rossi (Melbourne, 2014)
!
!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
!
  IMPLICIT NONE
!
  REAL (8) X,Y,Z,AX,AY,AZ,G,MDISC,AD,BD,R,CMD
!
  R = SQRT(X**2.0 + Y**2.0)
!
  CMD = -G*MDISC/(R**2.0 + (AD + SQRT(Z**2.0 + BD**2.0))**2.0)**(1.5)
!
! Compute the accelerations
  AX = CMD*X
  AY = CMD*Y
  AZ = CMD*Z*(AD + SQRT(Z**2.0 + BD**2.0))/SQRT(Z**2.0 + BD**2.0)
!
END SUBROUTINE FDISC
