SUBROUTINE FHALO (X,Y,Z,AX,AY,AZ,G,MHALO,AH,VHL,AHL,MHSER,REH,NH,GGH,BSERH,AAH,HCHOICE)
!
!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
!
! Compute the acceleration of a particle moving within the gravitational potential 
! generated by a a logarithmic/NFW/Sersic dark matter halo.
!
! Coded by L. J. Rossi (Melbourne, 2014)
!
!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
!
IMPLICIT NONE
!
  REAL (8) X,Y,Z,AX,AY,AZ,G,MHALO,AH,VHL,AHL,MHSER,REH,NH,HCHOICE,R,CMH,GGH,BSERH,AAH
!
  R = SQRT(X**2.0 + Y**2.0 + Z**2.0)
!
! Compute the accelerations
  IF (HCHOICE == 1.0D0) THEN
     CMH = -VHL**2.0/(AHL**2.0 + R**2.0)
     AX = CMH*X
     AY = CMH*Y
     AZ = CMH*Z
  ELSE IF (HCHOICE == 2.0) THEN
     CMH = -G*(MHALO/R**3.0*LOG(1 + R/AH) - MHALO/(AH*R**2.0)/(1 + R/AH))
     AX = CMH*X
     AY = CMH*Y
     AZ = CMH*Z
  ELSE IF (HCHOICE == 3.0) THEN
     CALL FSERSIC (X,Y,Z,AX,AY,AZ,G,MHSER,REH,NH,GGH,BSERH,AAH)
  END IF
!
END SUBROUTINE FHALO
