SUBROUTINE FSERSIC (X,Y,Z,AX,AY,AZ,G,M,RE,N,GG,B,AA)
!
!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
!
! Compute the acceleration of a particle moving within the potential generated by
! a Sérsic density profile.
!
! Coded by L. J. Rossi (Melbourne, 2014)
!
!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
!
  IMPLICIT NONE
!
  REAL (8) X,Y,Z,AX,AY,AZ,G,M,RE,N
  REAL (8) R,B,P,AA,XX,GI,GG
  REAL (8) GAMMDS,SCONST,IFAULT
!
  R = SQRT(X**2.0 + Y**2.0 + Z**2.0)
!
  XX = B*(R/RE)**(1.0/N)
  GI = GAMMDS (XX,AA,IFAULT)
  SCONST = -G*M/R**3.0*(GI/GG)
!
! Compute the accelerations
  AX = SCONST*X
  AY = SCONST*Y
  AZ = SCONST*Z
!  
END SUBROUTINE FSERSIC
